const dashboardRoutes = [
  // {
  //   path: "/#",
  //   name: "Business",
  //   namevi: "Kinh doanh",
  //   icon: "shopping_cart",
  //   layout: "/admin",
  //   parent: "operation",
  //   permission: "business",
  //   subMenu: [
  //     {
  //       path: "/order",
  //       name: "Order",
  //       namevi: "Đơn hàng",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "business_order",
  //     }
  //   ],
  // },
  {
    path: '/#',
    name: 'shopAdmin',
    icon: 'store_icon',
    layout: '/admin',
    parent: 'operation',
    permission: 'stocks',
    subMenu: [
      {
        path: '/qrManagement',
        name: 'qrManagement',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_qr',
      },
      {
        path: '/shopAdmin',
        name: 'shopManagement',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_shop',
      },
      {
        path: '/category',
        name: 'category',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_category',
      },
      {
        path: '/otherInformation',
        name: 'otherInfo',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_other_information',
      },
      {
        path: '/productApproval',
        name: 'productApproval',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_product_approval',
      },
      {
        path: '/broadcastMessages',
        name: 'broadcastMessages',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_broadcast',
      },
      {
        path: '/smsPackage',
        name: 'smsPackage',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_sms',
      },
      {
        path: '/advertisement',
        name: 'advertisement',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_advertisement',
      },
      {
        path: '/voucher',
        name: 'voucher',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_voucher',
      },
      {
        path: '/flashsale',
        name: 'flashSale',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_flashSale',
      },
    ],
  },
  {
    path: '/#',
    name: 'shopUser',
    icon: 'store_icon',
    layout: '/admin',
    parent: 'operation',
    permission: 'stocks',
    subMenu: [
      {
        path: '/shopProduct',
        name: 'product',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_shop',
      },
      {
        path: '/orderManagement',
        name: 'orderManagement',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_order_management',
      },
    ],
  },
  {
    path: '/#',
    name: 'game',
    icon: 'monetization_on_icon',
    layout: '/admin',
    parent: 'operation',
    permission: 'game',
    subMenu: [
      {
        path: '/game',
        name: 'game',
        layout: '/admin',
        parent: 'operation',
        permission: 'game',
      },
      {
        path: '/reportGame',
        name: 'reportGame',
        layout: '/admin',
        parent: 'operation',
        permission: 'game_report',
      },
    ],
  },
  {
    path: '/#',
    name: 'operationReport',
    icon: 'dashboard',
    layout: '/admin',
    parent: 'operation',
    permission: 'operationReport',
  },
  {
    path: '/#',
    name: 'uiManagement',
    icon: 'web_icon',
    layout: '/admin',
    parent: 'operation',
    permission: 'uiManagement',
  },
  // {
  //   path: '/#',
  //   name: 'Customers Manage',
  //   namevi: 'Khách hàng',
  //   icon: 'group_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'customersManage',
  // },
  // {
  //   path: '/tg-crm/chat',
  //   name: 'Chat',
  //   namevi: 'Tin nhắn',
  //   icon: 'chat_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'chat',
  // },
  // {
  //   path: '/tg-crm/rate',
  //   name: 'Rate',
  //   namevi: 'Đánh giá',
  //   icon: 'stars_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'rate',
  // },
  // {
  //   path: '/#',
  //   name: 'Notification',
  //   namevi: 'Thông báo',
  //   icon: 'notifications_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'notification',
  // },
  // {
  //   path: '/#',
  //   name: 'Interact',
  //   namevi: 'Tương tác',
  //   icon: 'linear_scale_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'interact',
  // },
  // {
  //   path: '/tg-ui/webbuilder',
  //   name: 'Web Builder',
  //   namevi: 'Trình tạo web',
  //   icon: 'web_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'webBuilder',
  // },
  // {
  //   path: '/#',
  //   name: 'Landing Page',
  //   namevi: 'Landing Page',
  //   icon: 'pages_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'landingPage',
  // },
  // {
  //   path: '/#',
  //   name: 'App Config',
  //   namevi: 'Cấu hình ứng dụng',
  //   icon: 'apps_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'appConfig',
  // },
  // {
  //   path: '/taskmanage',
  //   name: 'Task Manage',
  //   namevi: 'Quản lý công việc',
  //   icon: 'assignment_icon',
  //   layout: '/admin',
  //   parent: 'tg-task',
  //   permission: 'task_management',
  // },
  // {
  //   path: '/#',
  //   name: 'Task Report',
  //   namevi: 'Báo cáo công việc',
  //   icon: 'assignment_lateIcon',
  //   layout: '/admin',
  //   parent: 'tg-task',
  //   permission: 'taskReport',
  // },
  // {
  //   path: '/channel',
  //   name: 'Chanel',
  //   namevi: 'Kênh',
  //   icon: 'storefront_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'channel',
  // },
  // {
  //   path: '/#',
  //   name: 'Bus Manage',
  //   namevi: 'Doanh nghiệp',
  //   icon: 'settings_applications_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'busManage',
  // },
  // {
  //   path: '/#',
  //   name: 'User Manage',
  //   namevi: 'Người dùng',
  //   icon: 'group_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'userManage',
  // },
  // {
  //   path: '/#',
  //   name: 'Services & Fee',
  //   namevi: 'Dịch vụ & Phí',
  //   icon: 'room_service_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'services&Fee',
  // },
];

export default dashboardRoutes;
