/*!

=========================================================
* * natcash Platform v1.1.0 based on Material Dashboard React v1.9.0
=========================================================

* Product Page: https://www.microtec.vn/product/natcash
* Copyright 2021 Microtec (https://www.microtec.vn)
* Licensed under MIT (https://github.com/creativetimofficial/natcash/blob/master/LICENSE.md)

* Coded by Microtec

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
const dashboardRoutes = [
  // {
  //   path: "/#",
  //   name: "Business",
  //   namevi: "Kinh doanh",
  //   icon: "shopping_cart",
  //   layout: "/admin",
  //   parent: "operation",
  //   permission: "business",
  //   subMenu: [
  //     {
  //       path: "/order",
  //       name: "Order",
  //       namevi: "Đơn hàng",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "business_order",
  //     }
  //   ],
  // },
  {
    path: "/#",
    name: "shop",
    icon: "store_icon",
    layout: "/admin",
    parent: "operation",
    permission: "stocks",
    subMenu: [
      {
        path: "/qrManagement",
        name: "qrManagement",
        layout: "/admin",
        parent: "operation",
        permission: "shop_qr",
      },
      {
        path: "/shop",
        name: "shopManagement",
        layout: "/admin",
        parent: "operation",
        permission: "shop_shop",
      },
    ],
  },
  {
    path: "/#",
    name: "product",
    icon: "store_icon",
    layout: "/admin",
    parent: "operation",
    permission: "stocks",
    subMenu: [
      {
        path: "/category",
        name: "category",
        layout: "/admin",
        parent: "operation",
        permission: "product_category",
      },
      {
        path: "/otherInformation",
        name: "otherInfo",
        layout: "/admin",
        parent: "operation",
        permission: "product_category",
      },
      {
        path: "/productApproval",
        name: "productApproval",
        layout: "/admin",
        parent: "operation",
        permission: "product_approval",
      },
    ],
  },
  {
    path: "/#",
    name: "marketing",
    icon: "monetization_on_icon",
    layout: "/admin",
    parent: "operation",
    permission: "marketing",
    subMenu: [
      {
        path: "/#",
        name: "broadcastMessages",
        layout: "/admin",
        parent: "operation",
        permission: "marketing_broadcast",
      },
      {
        path: "/#",
        name: "smsPackage",
        layout: "/admin",
        parent: "operation",
        permission: "marketing_sms",
      },
      {
        path: "/#",
        name: "advertisement",
        layout: "/admin",
        parent: "operation",
        permission: "marketing_advertisement",
      },
      {
        path: "/voucher",
        name: "voucher",
        layout: "/admin",
        parent: "operation",
        permission: "marketing_voucher",
      },
      // {
      //   path: "/promotion",
      //   name: "Promotion",
      //   namevi: "Khuyến mãi",
      //   layout: "/admin",
      //   parent: "operation",
      //   permission: "marketing_promotion",
      // },
      // {
      //   path: "/combo",
      //   name: "Combo",
      //   namevi: "Combo khuyến mãi",
      //   layout: "/admin",
      //   parent: "operation",
      //   permission: "marketing_combo",
      // },
      // {
      //   path: "/dealshock",
      //   name: "Deal shock",
      //   namevi: "Deal sốc",
      //   layout: "/admin",
      //   parent: "operation",
      //   permission: "marketing_dealShock",
      // },
      {
        path: "/flashsale",
        name: "flashSale",
        layout: "/admin",
        parent: "operation",
        permission: "marketing_flashSale",
      },
      {
        path: "/game",
        name: "game",
        layout: "/admin",
        parent: "operation",
        permission: "game",
      },
    ],
  },
  {
    path: "/#",
    name: "operationReport",
    icon: "dashboard",
    layout: "/admin",
    parent: "operation",
    permission: "operationReport",
  },
  {
    path: "/#",
    name: "uiManagement",
    icon: "web_icon",
    layout: "/admin",
    parent: "operation",
    permission: "uiManagement",
  },
  // {
  //   path: "/#",
  //   name: "Config",
  //   namevi: "Cấu hình",
  //   icon: "ballot_icon",
  //   layout: "/admin",
  //   parent: "operation",
  //   permission: "config",
  //   subMenu: [
  //     {
  //       path: "/shop",
  //       name: "Shop",
  //       namevi: "Gian hàng",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "config_shop",
  //     },
  //     {
  //       path: "/staffmanage",
  //       name: "User Managent",
  //       namevi: "Quản lý người dùng",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "config_staffManage",
  //     },
  //     {
  //       path: "/employee",
  //       name: "Human Resource Management",
  //       namevi: "Quản lý nhân sự",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "config_humanResourceManage",
  //     },
  //     {
  //       path: "/customer",
  //       name: "Customer Management",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "config_customerManage",
  //     },
  //     {
  //       path: "/rolesmanager",
  //       name: "Subscription & payment",
  //       namevi: "Gói đăng ký và thanh toán",
  //       layout: "/admin",
  //       parent: "operation",
  //       permission: "config_rolesManager",
  //     },
  //   ],
  // },
  {
    path: "/#",
    name: "Customers Manage",
    namevi: "Khách hàng",
    icon: "group_icon",
    layout: "/admin",
    parent: "tg-crm",
    permission: "customersManage",
  },
  {
    path: "/tg-crm/chat",
    name: "Chat",
    namevi: "Tin nhắn",
    icon: "chat_icon",
    layout: "/admin",
    parent: "tg-crm",
    permission: "chat",
  },
  {
    path: "/tg-crm/rate",
    name: "Rate",
    namevi: "Đánh giá",
    icon: "stars_icon",
    layout: "/admin",
    parent: "tg-crm",
    permission: "rate",
  },
  {
    path: "/#",
    name: "Notification",
    namevi: "Thông báo",
    icon: "notifications_icon",
    layout: "/admin",
    parent: "tg-crm",
    permission: "notification",
  },
  {
    path: "/#",
    name: "Interact",
    namevi: "Tương tác",
    icon: "linear_scale_icon",
    layout: "/admin",
    parent: "tg-crm",
    permission: "interact",
  },
  {
    path: "/tg-ui/webbuilder",
    name: "Web Builder",
    namevi: "Trình tạo web",
    icon: "web_icon",
    layout: "/admin",
    parent: "tg-ui",
    permission: "webBuilder",
  },
  {
    path: "/#",
    name: "Landing Page",
    namevi: "Landing Page",
    icon: "pages_icon",
    layout: "/admin",
    parent: "tg-ui",
    permission: "landingPage",
  },
  {
    path: "/#",
    name: "App Config",
    namevi: "Cấu hình ứng dụng",
    icon: "apps_icon",
    layout: "/admin",
    parent: "tg-ui",
    permission: "appConfig",
  },
  {
    path: "/taskmanage",
    name: "Task Manage",
    namevi: "Quản lý công việc",
    icon: "assignment_icon",
    layout: "/admin",
    parent: "tg-task",
    permission: "task_management",
  },
  {
    path: "/#",
    name: "Task Report",
    namevi: "Báo cáo công việc",
    icon: "assignment_lateIcon",
    layout: "/admin",
    parent: "tg-task",
    permission: "taskReport",
  },
  {
    path: "/channel",
    name: "Chanel",
    namevi: "Kênh",
    icon: "storefront_icon",
    layout: "/admin",
    parent: "system",
    permission: "channel",
  },
  {
    path: "/#",
    name: "Bus Manage",
    namevi: "Doanh nghiệp",
    icon: "settings_applications_icon",
    layout: "/admin",
    parent: "system",
    permission: "busManage",
  },
  {
    path: "/#",
    name: "User Manage",
    namevi: "Người dùng",
    icon: "group_icon",
    layout: "/admin",
    parent: "system",
    permission: "userManage",
  },
  {
    path: "/#",
    name: "Services & Fee",
    namevi: "Dịch vụ & Phí",
    icon: "room_service_icon",
    layout: "/admin",
    parent: "system",
    permission: "services&Fee",
  },
];

export default dashboardRoutes;
