const dashboardRoutes = [
  {
    path: '/#',
    name: 'shopAdmin',
    icon: 'store_icon',
    layout: '/admin',
    parent: 'operation',
    permission: 'stocks',
    subMenu: [
      // {
      //   path: '/qrManagement',
      //   name: 'qrManagement',
      //   layout: '/admin',
      //   parent: 'operation',
      //   permission: 'shop_admin_qr',
      // },
      {
        path: '/shop-management',
        name: 'shop_management',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_shop',
      },
      {
        path: '/category',
        name: 'category',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_category',
      },
      // {
      //   path: '/otherInformation',
      //   name: 'otherInfo',
      //   layout: '/admin',
      //   parent: 'operation',
      //   permission: 'shop_admin_other_information',
      // },
      {
        path: '/product-approval',
        name: 'productApproval',
        layout: '/admin',
        parent: 'operation',
        permission: 'shop_admin_product_approval',
      },
      // {
      //   path: '/advertisement',
      //   name: 'advertisement',
      //   layout: '/admin',
      //   parent: 'operation',
      //   permission: 'marketing_advertisement',
      // },
      {
        path: '/voucher',
        name: 'voucher',
        layout: '/admin',
        parent: 'operation',
        permission: 'marketing_voucher',
      },
      {
        path: '/program-voucher-approval',
        name: 'voucherProgramApproval',
        layout: '/admin',
        parent: 'operation',
        permission: 'admin_program_voucher_approval',
      },
      // {
      //   path: '/flashsale',
      //   name: 'flashSale',
      //   layout: '/admin',
      //   parent: 'operation',
      //   permission: 'marketing_flashSale',
      // },
      {
        path: '/game',
        name: 'game',
        layout: '/admin',
        parent: 'operation',
        permission: 'admin_game',
      },
      {
        path: '/report-game',
        name: 'report_game',
        layout: '/admin',
        parent: 'operation',
        permission: 'admin_game_report',
      },
    ],
  },
  {
    path: '/#',
    name: 'shopUser',
    icon: 'store_icon',
    layout: '/shop',
    parent: 'operation',
    permission: 'stocks',
    subMenu: [
      {
        path: '/product',
        name: 'my_products',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_my_products',
      },
      // {
      //   path: '/order-management',
      //   name: 'order_management',
      //   layout: '/shop',
      //   parent: 'operation',
      //   permission: 'shop_order_management',
      // },
      // {
      //   path: '/interface-management',
      //   name: 'interface_management',
      //   layout: '/shop',
      //   parent: 'operation',
      //   permission: 'shop_interface_management',
      // },
      {
        path: '/broadcast-messages',
        name: 'broadcastMessages',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_marketing_broadcast',
      },
      {
        path: '/flash-sale-shop',
        name: 'flashSaleShop',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_voucher_coupon',
      },
      {
        path: '/flash-sale-natshop',
        name: 'flashSaleNatShop',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_voucher_coupon',
      },
      {
        path: '/shop-infomation',
        name: 'shopInformation',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_voucher_coupon',
      },
      {
        path: '/voucher-coupon',
        name: 'voucher_coupon',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_voucher_coupon',
      },
      {
        path: '/sms-messages',
        name: 'smsPackage',
        layout: '/shop',
        parent: 'operation',
        permission: 'shop_sms_message',
      },
      // {
      //   path: '/voucher',
      //   name: 'voucher',
      //   layout: '/shop',
      //   parent: 'operation',
      //   permission: 'shop_voucher',
      // },
    ],
  },
  {
    path: '/#',
    name: 'operationReport',
    icon: 'dashboard',
    layout: '/admin',
    parent: 'operation',
    permission: 'operationReport',
  },
  // {
  //   path: '/#',
  //   name: 'uiManagement',
  //   icon: 'web_icon',
  //   layout: '/admin',
  //   parent: 'operation',
  //   permission: 'uiManagement',
  // },
  // {
  //   path: '/#',
  //   name: 'Customers Manage',
  //   namevi: 'Khách hàng',
  //   icon: 'group_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'customersManage',
  // },
  // {
  //   path: '/tg-crm/chat',
  //   name: 'Chat',
  //   namevi: 'Tin nhắn',
  //   icon: 'chat_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'chat',
  // },
  // {
  //   path: '/tg-crm/rate',
  //   name: 'Rate',
  //   namevi: 'Đánh giá',
  //   icon: 'stars_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'rate',
  // },
  // {
  //   path: '/#',
  //   name: 'Notification',
  //   namevi: 'Thông báo',
  //   icon: 'notifications_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'notification',
  // },
  // {
  //   path: '/#',
  //   name: 'Interact',
  //   namevi: 'Tương tác',
  //   icon: 'linear_scale_icon',
  //   layout: '/admin',
  //   parent: 'tg-crm',
  //   permission: 'interact',
  // },
  // {
  //   path: '/tg-ui/webbuilder',
  //   name: 'Web Builder',
  //   namevi: 'Trình tạo web',
  //   icon: 'web_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'webBuilder',
  // },
  // {
  //   path: '/#',
  //   name: 'Landing Page',
  //   namevi: 'Landing Page',
  //   icon: 'pages_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'landingPage',
  // },
  // {
  //   path: '/#',
  //   name: 'App Config',
  //   namevi: 'Cấu hình ứng dụng',
  //   icon: 'apps_icon',
  //   layout: '/admin',
  //   parent: 'tg-ui',
  //   permission: 'appConfig',
  // },
  // {
  //   path: '/taskmanage',
  //   name: 'Task Manage',
  //   namevi: 'Quản lý công việc',
  //   icon: 'assignment_icon',
  //   layout: '/admin',
  //   parent: 'tg-task',
  //   permission: 'task_management',
  // },
  // {
  //   path: '/#',
  //   name: 'Task Report',
  //   namevi: 'Báo cáo công việc',
  //   icon: 'assignment_lateIcon',
  //   layout: '/admin',
  //   parent: 'tg-task',
  //   permission: 'taskReport',
  // },
  // {
  //   path: '/channel',
  //   name: 'Chanel',
  //   namevi: 'Kênh',
  //   icon: 'storefront_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'channel',
  // },
  // {
  //   path: '/#',
  //   name: 'Bus Manage',
  //   namevi: 'Doanh nghiệp',
  //   icon: 'settings_applications_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'busManage',
  // },
  // {
  //   path: '/#',
  //   name: 'User Manage',
  //   namevi: 'Người dùng',
  //   icon: 'group_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'userManage',
  // },
  // {
  //   path: '/#',
  //   name: 'Services & Fee',
  //   namevi: 'Dịch vụ & Phí',
  //   icon: 'room_service_icon',
  //   layout: '/admin',
  //   parent: 'system',
  //   permission: 'services&Fee',
  // },
];

export default dashboardRoutes;
