const customerManagementText = [
  {
    id: "en",
    title: "Customer Management",
    search: {
      keyWord: "Keyword",
      customerGroup: "Customer group",
      active: "Active",
    },
    placeholder: {
      choosevalue: "Choose the value below",
    },
    button: {
      search: "Search",
      addBtn: "Add",
      exportFile: "Export file",
      account: "Account",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
    },
    table: {
      header: [
        "#",
        "Customer name",
        "Customer group",
        "Phone",
        "Address",
        "Email",
        "Act",
      ],
      headerModal: ["#", "Id", "Name"],
    },
    modal: {
      title: "Customer information",
      fields: {
        customerCode: "Customer Code",
        isActive: "Active",
        isAppliedDiscount: "Apply Discount",
        fullname: "Full name",
        address: "Address",
        customerGroup: "Customer Group",
        email: "Email",
        phoneNumber: "Phone number",
        province: "Province",
        district: "District",
        idCardNumber: "Id Card Number",
        fax: "Fax",
        account: "Account",
        bank: "Bank",
        note: "Note",
      },
    },
  },
  {
    id: "vi",
    title: "Quản lý khách hàng",
    search: {
      keyWord: "Từ khoá",
      customerGroup: "Nhóm khách hàng",
      active: "Hoạt động",
    },
    placeholder: {
      choosevalue: "Chọn giá trị bên dưới",
    },
    button: {
      search: "Tìm kiếm",
      addBtn: "Thêm",
      exportFile: "Xuất file",
      account: "Tài khoản",
      edit: "Sửa",
      save: "Lưu",
      cancel: "Huỷ",
      delete: "Xoá",
    },
    table: {
      header: [
        "#",
        "Tên Khách Hàng",
        "Nhóm Khách Hàng",
        "Điện Thoại",
        "Địa Chỉ",
        "Email",
        "Hành động",
      ],
      headerModal: ["#", "Mã", "Tên"],
    },
    modal: {
      title: "Thông tin khách hàng",
      fields: {
        customerCode: "Mã khách hàng",
        isActive: "Kích hoạt",
        isAppliedDiscount: "Áp dụng chiết khấu",
        fullname: "Họ tên",
        address: "Địa chỉ",
        customerGroup: "Nhóm khách hàng",
        email: "Email",
        phoneNumber: "Số điện thoại",
        province: "Tỉnh thành",
        district: "Quận huyện",
        idCardNumber: "CMND",
        fax: "Fax",
        account: "Tài Khoản",
        bank: "Ngân hàng",
        note: "Ghi chú",
      },
    },
  },
];

export default customerManagementText;
